# Generated by Django 4.2.4 on 2023-08-20 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'My suoer user', 'verbose_name_plural': 'My suoer users'},
        ),
    ]
