# Generated by Django 4.2.4 on 2023-08-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'My super user', 'verbose_name_plural': 'My super users'},
        ),
    ]
